# Generated by Django 3.2.9 on 2022-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PRODUCT/2022/02/01/12/17/2915589b1b055848f8a56cfb06e6185f9d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='PRODUCT/2022/02/01/12/17/2915589b1b055848f8a56cfb06e6185f9d/'),
        ),
    ]
