# Generated by Django 3.2.9 on 2022-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220201_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PRODUCT/2022/02/01/13/32/2038aa80e1c7534849b288fd7981cf1cbc/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='PRODUCT/2022/02/01/13/32/2038aa80e1c7534849b288fd7981cf1cbc/'),
        ),
    ]
