# Generated by Django 3.2.9 on 2022-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_euser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='permission',
            field=models.CharField(choices=[('0', 'Super Admin'), ('1', 'Admin'), ('2', 'Individual'), ('3', 'Guest')], default='0', max_length=100),
        ),
    ]
